global:
  resolve_timeout: 5m

route:
  receiver: 'mail'

receivers:
- name: 'mail'
  email_configs:
  - to: 'youremail@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'smtp_user'
    auth_password: 'smtp_password'
