services:

  prometheus:
    image: prom/prometheus:v3.6.0
    user: "1000:1000"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - ./prometheus/data:/prometheus/data
      - ./password.txt:/etc/prometheus/password.txt:ro
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  grafana:
    image: grafana/grafana:12.0.1
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana
    hostname: grafana
    restart: always
    environment:
      TZ: "Europe/Moscow"
      GF_SERVER_ROOT_URL: "http://localhost:3000/"
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    hostname: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - default

  wordpress:
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress
    hostname: wordpress
    volumes:
      - ./wordpress/data:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpressdb
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.4.6
    container_name: db
    hostname: db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - default

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - ./wordpress/data:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-conf/conf.d:/etc/nginx/conf.d:ro
    networks:
      - default

  mysql_exporter:
    image: prom/mysqld-exporter:v0.18.0
    container_name: mysql_exporter
    ports:
      - "9104:9104"
    volumes:
      - ./exporters/mysqld/.my.cnf:/.my.cnf
    networks:
      - default

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.27.0
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./exporters/blackbox/blackbox.yml:/config/blackbox.yml
      - ./exporters/blackbox/web-config.yml:/config/web-config.yml:ro
#      - ./exporters/blackbox/certs:/certs:ro
    command:
      - '--config.file=/config/blackbox.yml'
      - '--web.config.file=/config/web-config.yml'
    networks:
      - default

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.127.0
    container_name: victoriametrics
    volumes:
      - ./victoriametrics/data:/victoria-metrics-data
    ports:
      - '8428:8428'
    command: 
      - '--retentionPeriod=2w'
    depends_on:
      - prometheus
    

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
