groups:
- name: Mycomp_alerts
  rules:
  - alert: Database_is_Down
    expr: up{job="MySQL"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Сервис на сервере {{ $labels.instance }} недоступен"
      description: "Возможно сервис упал или сервер недоступен. Значение метрики up = {{ $value }}"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance)(rate(windows_cpu_time_total{mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Высокая загрузка CPU на {{ $labels.instance }}"
      description: "Загрузка CPU выше 90% в течение 5 минут. Текущие данные: {{ $value }}"

  - alert: HighLogicalDiskUsage
    expr: (windows_logical_disk_size_bytes - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes * 100 < 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Мало места на диске на сервере {{ $labels.instance }}"
      description: "Осталось места на диске меньше 20%. Текущие данные: {{ $value }}"